// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/MastoCred-Inc/web-app/models"
)

type RegisterUser struct {
	Email         string `json:"email"`
	Lastname      string `json:"lastname"`
	Firstname     string `json:"firstname"`
	Password      string `json:"password"`
	PasswordMatch string `json:"passwordMatch"`
}

type RegisterWaitlist struct {
	FullName     string              `json:"fullName"`
	Email        string              `json:"email"`
	Telephone    string              `json:"telephone"`
	BusinessName *string             `json:"businessName"`
	Mode         models.WaitlistMode `json:"mode"`
}

type UserAuthenticated struct {
	Token string       `json:"token"`
	User  *models.User `json:"user"`
}

type Waitlist struct {
	ID           string              `json:"id"`
	FullName     *string             `json:"fullName"`
	BusinessName *string             `json:"businessName"`
	Email        string              `json:"email"`
	Telephone    string              `json:"telephone"`
	Mode         models.WaitlistMode `json:"mode"`
}
