// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/MastoCred-Inc/web-app/models"
)

type LoginUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterUser struct {
	Email         string `json:"email"`
	Lastname      string `json:"lastname"`
	Firstname     string `json:"firstname"`
	Password      string `json:"password"`
	PasswordMatch string `json:"passwordMatch"`
}

type UserAuthenticated struct {
	Token string       `json:"token"`
	User  *models.User `json:"user"`
}
